FROM continuumio/anaconda3
MAINTAINER Anbarasan ss.anbuselvan@gmail.com


# 1. RUN
#RUN /opt/conda/bin/conda install jupyter -y --quiet 
#RUN pip install simplejson
#RUN mkdir /opt/notebooks





# 2. Copy the Source code
COPY . /src
